### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by davismartin** [adamcweitzman/portfolio-blog#1]
hmm... to me I think this:

``` js
 $('.btn').hover(function() {
        $(this).css({'background-color': 'transparent', 'color': 'black' });
    }, function() {
        $(this).css({'background-color': '#9C66BA', 'color': 'white'});
    });
```

Should live in the Css using the pseudo-class

``` css
// might want to rename this project-button most of the time classes or ids hyphenated not camel cased
#projectButton {
  // Looks like this already in your css just getting overwritten by js 
  background-color: '#9C66BA'
  color: 'white'
}
#projectButton:hover {
  background-color: 'transparent'
  color: 'black'
}
```
